// Automatically generated by astro-icon
// af1a857011207578bd70fe90e382f0480f63ec1f7c3f574da4c4873f2ef424fd

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "menu/about"
		| "menu/blog"
		| "menu/bodybuilding"
		| "menu/book"
		| "menu/categories"
		| "menu/contact"
		| "menu/cube"
		| "menu/friend"
		| "menu/heart"
		| "menu/home"
		| "menu/post"
		| "menu/project"
		| "menu/skill"
		| "menu/support"
		| "social/bilibili"
		| "social/github"
		| "social/tiktok"
		| "social/weibo"
		| "social/zhihu";
}