// Automatically generated by astro-icon
// 99ba0dcdb5b7043021f5e7775db22ec3313a4fa2111eff91dec60b56cde2707a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "menu/about"
		| "menu/blog"
		| "menu/bodybuilding"
		| "menu/book"
		| "menu/categories"
		| "menu/contact"
		| "menu/cube"
		| "menu/friend"
		| "menu/heart"
		| "menu/home"
		| "menu/post"
		| "menu/project"
		| "menu/support"
		| "social/bilibili"
		| "social/github"
		| "social/rss"
		| "social/support"
		| "social/tiktok"
		| "social/weibo"
		| "social/zhihu";
}