// Automatically generated by astro-icon
// 286364fe95f60cef935babe2cbce2cffca51085d6d8ff149a76ffd5b93aec385

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "menu/about"
		| "menu/blog"
		| "menu/book"
		| "menu/categories"
		| "menu/contact"
		| "menu/cube"
		| "menu/friend"
		| "menu/heart"
		| "menu/home"
		| "menu/post"
		| "menu/project"
		| "menu/support"
		| "social/bilibili"
		| "social/github"
		| "social/rss"
		| "social/support"
		| "social/tiktok"
		| "social/weibo"
		| "social/zhihu";
}